import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import chalk from "chalk";

const SAMPLE_FILENAME = "confluence-sample.md";

const SAMPLE_CONTENT = `# My Confluence Page

This is a sample markdown file demonstrating features supported by md2cf.

## Table of Contents

## Introduction

This document shows how to write markdown that converts cleanly to Confluence pages.
md2cf automatically converts this Table of Contents section into a Confluence TOC macro.

## Text Formatting

You can use **bold**, *italic*, ~~strikethrough~~, and \`inline code\` formatting.

Combine them for **_bold italic_** text or **\`bold code\`**.

## Lists

### Bullet List

- First item
- Second item
  - Nested item
  - Another nested item
- Third item

### Numbered List

1. Step one
2. Step two
   1. Sub-step A
   2. Sub-step B
3. Step three

## Code

Inline code: \`const x = 42;\`

Fenced code block with syntax highlighting:

\`\`\`typescript
interface Config {
  email: string;
  token: string;
  baseUrl: string;
}

function loadConfig(): Config {
  return JSON.parse(readFileSync("config.json", "utf-8"));
}
\`\`\`

## Tables

| Feature | Supported | Notes |
|---------|-----------|-------|
| Bold | Yes | Use \`**text**\` |
| Italic | Yes | Use \`*text*\` |
| Tables | Yes | Standard markdown tables |
| Images | Yes | Local and remote URLs |
| Mermaid | Yes | Requires mmdc installed |

## Links and Images

- [Atlassian Documentation](https://developer.atlassian.com/cloud/confluence/)
- [md2cf on npm](https://www.npmjs.com/package/md2cf)

## Blockquotes

> This is a blockquote.
> It can span multiple lines.
>
> And have multiple paragraphs.

## Panels

> [!NOTE]
> This is an informational note converted to a Confluence info panel.

> [!TIP]
> This is a tip converted to a Confluence success panel.

> [!WARNING]
> This is a warning converted to a Confluence warning panel.

## Expand/Collapse

:::expand Click to see hidden content
This content is collapsed by default on Confluence.

- You can include lists
- And **formatted** text
:::

## Other Features

### Horizontal Rule

---

### Mermaid Diagrams

If you have mmdc installed, mermaid code blocks are rendered as images:

\`\`\`mermaid
graph TD
    A[Start] --> B{Is it working?}
    B -->|Yes| C[Great!]
    B -->|No| D[Debug]
    D --> A
\`\`\`

---

*This sample was generated by \`md2cf init\`. Edit it to match your content, then sync with:*

\`\`\`bash
md2cf ${SAMPLE_FILENAME} <your-confluence-page-url>
\`\`\`
`;

/**
 * Create a sample markdown file in the current directory.
 */
export function initAction(): void {
  const targetPath = resolve(process.cwd(), SAMPLE_FILENAME);

  if (existsSync(targetPath)) {
    console.log(chalk.yellow(`${SAMPLE_FILENAME} already exists in the current directory.`));
    console.log(chalk.dim("Delete it first if you want to regenerate."));
    return;
  }

  writeFileSync(targetPath, SAMPLE_CONTENT, "utf-8");

  console.log(chalk.green.bold(`Created ${SAMPLE_FILENAME}`));
  console.log();
  console.log(chalk.dim("Next steps:"));
  console.log(chalk.dim("  1. Edit the file to match your content"));
  console.log(chalk.dim("  2. Configure credentials: ") + "md2cf config");
  console.log(
    chalk.dim("  3. Sync to Confluence:   ") +
      `md2cf ${SAMPLE_FILENAME} <your-confluence-page-url>`,
  );
}
